webtalk_init -webtalk_dir D:\\ADS\\SoC_Intr_cache\\SoC_Intr_cache.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-12-29 18:34:43" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "533n1vr64ejmo20m8nrrhr49sd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.087 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1514552431806" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key Processors -value "3" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1514552431806"
webtalk_add_data -client sdk -key uid -value "1514552446334" -context "sdk\\\\bsp/1514552446334"
webtalk_add_data -client sdk -key hwid -value "1514552431806" -context "sdk\\\\bsp/1514552446334"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1514552446334"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1514552446334"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1514552446334"
webtalk_add_data -client sdk -key uid -value "1514552447138" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key hwid -value "1514552431806" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key bspid -value "1514552446334" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key projSize -value "96.3984375" -context "sdk\\\\application/1514552447138"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1514552683064"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1514552683064"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1514552683064"
webtalk_add_data -client sdk -key DebugCount -value "4" -context "sdk\\\\bsp/1514552683064"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1514552683064"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1514552683064"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1514552683064"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1514552683064"
webtalk_transmit -clientid 137722602 -regid "" -xml D:\\ADS\\SoC_Intr_cache\\SoC_Intr_cache.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\ADS\\SoC_Intr_cache\\SoC_Intr_cache.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\ADS\\SoC_Intr_cache\\SoC_Intr_cache.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
